//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho1Bim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCompra
    {
        public int idItemCompra { get; set; }
        public double precoUnitario { get; set; }
        public int quantidade { get; set; }
        public int Produto_idProduto { get; set; }
        public int Compra_idCompra { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Compra Compra { get; set; }
    }
}
